### ISSUE TITLE
Which signals should i_wb_data_stb and i_wb_ctrl_stb connect to wishbone? 

### ISSUE THREAD

**Issue by CaoE** [ZipCPU/s6soc#1]
Hi~
Which signals should i_wb_data_stb and i_wb_ctrl_stb connect to wishbone? Should o_qspi_mod connect to  IO3 and io4 of flash in wbqspiflash.v

**Comment by ZipCPU** [comment]
The QSPI flash drive, wbqspiflash, has two WB ports.  One is a data port, the other the control port.  The two ports share all the same signals, save the strobe signal which indicates which of the two ports is being active.  The basic logic within the interconnect is: data_stb = (data_address)&&(wb_stb) and likewise ctrl_stb = (data_address)&&(wb_stb).

Only the alternate build, however, uses the wbqspiflash controller.  It took up too much logic to use with the CPU in place as well.  The CPU design uses the qflashxpress.v module instead for its Quad SPI interactions.  This module, however, has no control port and so it can do nothing more than read from the flash.

If OpenCores were up, I'd point you to a link for the wbqspiflash project from which this file is drawn.  There's a nice spec sheet there describing how it needs to be hooked up.
